import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim':            '#bfc8d0',
        'primary-container':             '#0052ff',
        'surface-container-high':        '#e6e8ea',
        'on-secondary-fixed-variant':    '#005143',
        'on-primary-container':          '#dfe3ff',
        'surface-variant':               '#e0e3e5',
        'error-container':               '#ffdad6',
        'outline':                       '#737688',
        'surface-container-low':         '#f2f4f6',
        'inverse-on-surface':            '#eff1f3',
        'surface-dim':                   '#d8dadc',
        'on-error-container':            '#93000a',
        'primary-fixed':                 '#dde1ff',
        'primary':                       '#003ec7',
        'secondary-fixed':               '#58fbda',
        'background':                    '#f7f9fb',
        'on-tertiary-fixed':             '#141d23',
        'inverse-primary':               '#b7c4ff',
        'inverse-surface':               '#2d3133',
        'on-surface-variant':            '#434656',
        'surface-container-lowest':      '#ffffff',
        'surface':                       '#f7f9fb',
        'on-background':                 '#191c1e',
        'on-surface':                    '#191c1e',
        'surface-container-highest':     '#e0e3e5',
        'tertiary-fixed':                '#dbe4ed',
        'surface-container':             '#eceef0',
        'secondary':                     '#006b5a',
        'on-tertiary':                   '#ffffff',
        'on-primary-fixed-variant':      '#0038b6',
        'on-secondary-fixed':            '#00201a',
        'on-error':                      '#ffffff',
        'secondary-container':           '#54f8d7',
        'surface-tint':                  '#004ced',
        'surface-bright':                '#f7f9fb',
        'error':                         '#ba1a1a',
        'on-secondary':                  '#ffffff',
        'on-tertiary-container':         '#dde6ef',
        'outline-variant':               '#c3c5d9',
        'primary-fixed-dim':             '#b7c4ff',
        'on-primary-fixed':              '#001452',
        'tertiary':                      '#464f56',
        'on-tertiary-fixed-variant':     '#3f484f',
        'on-primary':                    '#ffffff',
        'tertiary-container':            '#5e676f',
        'secondary-fixed-dim':           '#2cdebf',
        'on-secondary-container':        '#00705e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        xs:               '4px',
        sm:               '12px',
        base:             '8px',
        md:               '24px',
        lg:               '48px',
        xl:               '80px',
        gutter:           '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-lg':        ['Manrope', 'sans-serif'],
        'headline-md':        ['Manrope', 'sans-serif'],
        'body-lg':            ['Manrope', 'sans-serif'],
        'body-md':            ['Manrope', 'sans-serif'],
        'caption':            ['Manrope', 'sans-serif'],
        'label-caps':         ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg':        ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':        ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'caption':            ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps':         ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

export default config;
